### ISSUE TITLE
Thrid party librarys python // pkgsrc

### ISSUE THREAD

**Issue by Noveel** [salmoh/lifelike#8]
Good afternoon,
I asked Dr. Hamburger how to use third party libraries in python. He wrote me that the best way of doing so is using pkgsrc and sending a whole python environment with our project...

I think this is similar to the virtual environment Salman showed us. Do you know how to setup pkgsrc Salman??
http://pkgsrc.org/
http://wiki.netbsd.org/pkgsrc/how_to_use_pkgsrc_on_linux/

**Comment by salmoh** [comment]
Yeah. Salmoh is my username on my Github not my name :)

**Comment by Noveel** [comment]
Oh, sorry ;).

That would be nice.

**Comment by salmoh** [comment]
I think that we have to use [pkgsrc](https://en.wikipedia.org/wiki/Pkgsrc) (the default package manager of [NetBSD](https://en.wikipedia.org/wiki/NetBSD)) to build [pip](https://en.wikipedia.org/wiki/Pip_%28package_manager%29) and after that we can install the modules we want using pip.

**Comment by Noveel** [comment]
Dr. Harenberg will upload a working version of pkgsrc with numpy

**Comment by salmoh** [comment]
+1

**Comment by salmoh** [comment]
:+1:
